### ISSUE TITLE
I need HELP!!!

### ISSUE THREAD

**Issue by zsq19958629** [thomasvt1/HomeAssistant#2]
Machine environment:
Intel ATOM N2600, 2 gb RAM, 32 gb SSD.
Lede for OpenWRT Linux runs docker. Docker manages UI as "DockerFly".
After pulling the image, load "/root/.homeassistant" into the "/ MNT /sda5/docker/hass" directory.
Map port "TCP /8123:8123", network configuration "bridge" mode, create container start.
However, the port 8123 cannot be accessed. After entering the container, the port 8123 is not open through netstat -ntpl.
Indicates how it should be configured.

My English is very poor, this paragraph is machine translation

**Comment by thomasvt1** [comment]
Hi, are files created in the directory?

I assume the spaced in your "/mnt" are not on purpose right?

**Comment by zsq19958629** [comment]
Sorry, the space in this path is caused by machine translation."/mnt/sda5/docker/hass"

**Comment by thomasvt1** [comment]
> Sorry, the space in this path is caused by machine translation."/mnt/sda5/docker/hass"

And what's inside that directory? And what does the log say?

**Comment by zsq19958629** [comment]
home-asshstant.log
`2019-04-07 15:24:00 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package pyotp==2.2.6: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f63143274e0>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/pyotp/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6314327400>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/pyotp/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f63143274a8>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/pyotp/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f63143273c8>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/pyotp/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6314327358>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/pyotp/
  Could not find a version that satisfies the requirement pyotp==2.2.6 (from versions: )
No matching distribution found for pyotp==2.2.6
2019-04-07 15:24:00 ERROR (MainThread) [homeassistant.requirements] Not initializing homeassistant.auth.mfa_modules.totp because could not install requirement pyotp==2.2.6
2019-04-07 15:24:00 ERROR (MainThread) [homeassistant.bootstrap] Home Assistant core failed to initialize. Further initialization aborted
`

/mnt/sda5/docker/hass
There are some yaml configuration files, a log file, and a DEPS directory in the directory.

**Comment by thomasvt1** [comment]
Could you pull the latest image and try it again?

**Comment by zsq19958629** [comment]
Well. I'll try again right away.

**Comment by zsq19958629** [comment]
`root@1df50ce4e1a0:/$ nslookup www.163.com
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'www.163.com': Try again`

I tried it out. In the container, only 192.168.1.x LAN network can be accessed, but the Internet network can not be accessed. As a result, Alpine in the container can not download and install the network.
How to solve this problem?
ping www.msn.com error
ping 192.168.1.30 ok

**Comment by zsq19958629** [comment]
It has been determined that the factors of network configuration cause docker cannot access the Internet. Use the command line mode to launch dockers and add "docker run --net host... ', is now accessible through port 8123, but there are several errors in the log that do not seem to be serious.

**Comment by thomasvt1** [comment]
Glad you solved it!
