### ISSUE TITLE
mariadb with `full`?

### ISSUE THREAD

**Issue by tadly** [thomasvt1/HomeAssistant#3]
If I got this right, `latest` uses [your requirements](https://raw.githubusercontent.com/thomasvt1/HomeAssistant/requirements/requirements.txt) which would contain `pymysql` and some other (possibly useful) stuff.

`full` on the other hand is purely based on homeassistants `requirements_all.txt` which **does not** include _random_ db drivers which does make sense.

I'm curious if you'd be willing to add [your requirements](https://raw.githubusercontent.com/thomasvt1/HomeAssistant/requirements/requirements.txt) to the `full` tag or maybe introduce a new tag which would be based on both your and homeassistants `requirements_all.txt` (not sure about a name for it yet)?

**Comment by thomasvt1** [comment]
I see the potential for that 👍 

I've added an `extra` branch wich should start building this night based on my requirements + requirements_all.txt

**Comment by tadly** [comment]
Awesome, thanks a bunch :)
