### ISSUE TITLE
full, extra and dev branches not building

### ISSUE THREAD

**Issue by tadly** [thomasvt1/HomeAssistant#4]
`full` and `extra` builds are both a month old and `dev` is 9 days behind it seems.

Do you know why?

**Comment by thomasvt1** [comment]
Seems like Home Assistant added some build dependencies, added them now and we will see if it works.

**Comment by thomasvt1** [comment]
![image](https://user-images.githubusercontent.com/2271011/60910690-c28cd080-a281-11e9-99f4-99e3b31cefea.png)
All images are building agains, thanks for the heads up! @tadly

**Comment by tadly** [comment]
@thomasvt1 Sure thing. Thanks for the quick fix :)

**Comment by tadly** [comment]
I think it's happening again. I'm currently _stuck_ on 0.95.4. Mind having another look? :)
![2019-07-22_08:45:1563777935](https://user-images.githubusercontent.com/503647/61611816-1bcf0980-ac5d-11e9-8433-f0d7fba59537.png)

**Comment by thomasvt1** [comment]
Looks like they changed something that broke with the parameters again; removed that parameter from all builds let's wait and see

![image](https://user-images.githubusercontent.com/2271011/61612897-1b843d80-ac60-11e9-9421-14fce9a7c9a4.png)
