### ISSUE TITLE
how to run this docker?

### ISSUE THREAD

**Issue by zsq19958629** [thomasvt1/HomeAssistant#5]
docker run ----?????
tks

**Comment by thomasvt1** [comment]
I personally use this command;

```docker run -d --name='homeassistant' --net='host' -e TZ="Europe/Berlin" -e 'TCP_PORT_8123'='8123' -e 'PUID'='99' -e 'PGID'='100' -v '/mnt/user/appdata/homeassistant':'/config':'rw' 'thomasvt1/homeassistant'```
