### ISSUE TITLE
How to get the 'requirements.txt' file

### ISSUE THREAD

**Issue by icofans** [thomasvt1/HomeAssistant#6]
https://raw.githubusercontent.com/thomasvt1/HomeAssistant/requirements/requirements.txt Unable to access

**Comment by thomasvt1** [comment]
That's strange, when I click on your link it works. Have you tried curl/ a different browser?

![image](https://user-images.githubusercontent.com/2271011/108876589-ac6e8800-75fe-11eb-9edd-a3e9a0560a64.png)
